### ISSUE TITLE
Implementing/Refactoring the VLAN assignment on L2 paths.

### ISSUE THREAD

**Issue by YufengXin** [atlanticwave-sdx/pce#101]
We would assume every domain by default does VLAN translation on the border interfaces. 
(1) Maintaining the VLAN resource pool: add/delete/reserved/released 
(2) Assigning VLAN tags to the per-domain segments of computed paths.

**Comment by YufengXin** [comment]
FIU input: the vlan ranges on the two ports on an inter-domain link should be the same (pre-agreed upon by the admin). So (1) need a validation check when adding topologies on this; (2) vlan translation happens in a domain. vlan assignment becomes simpler after the path is obtained.
An manual configuration example over 3 domains (2 inter-domain links) from Mert/Itlo: the vlan path: 201-202-202-203-203-201.

# Amlight domain
curl -H 'Content-type: application/json' -X POST $AMLIGHT/api/kytos/mef_eline/v2/evc -d '{"name": "AMLIGHT_vlan_201_202_Ampath_Tenet", "dynamic_backup_path": true, "uni_a": {"tag": {"value": 201, "tag_type": 1}, "interface_id": "aa:00:00:00:00:00:00:03:50"}, "uni_z": {"tag": {"value": 202, "tag_type": 1}, "interface_id": "aa:00:00:00:00:00:00:01:40"}}'

# SAX domain
curl -H 'Content-type: application/json' -X POST $SAX/api/kytos/mef_eline/v2/evc -d '{"name": "SAX_vlan_202_203_Ampath_Tenet", "dynamic_backup_path": true, "uni_a": {"tag": {"value": 202, "tag_type": 1}, "interface_id": "dd:00:00:00:00:00:00:04:40"}, "uni_z": {"tag": {"value": 203, "tag_type": 1}, "interface_id": "dd:00:00:00:00:00:00:05:41"}}'

# TENET domain
curl -H 'Content-type: application/json' -X POST $TENET/api/kytos/mef_eline/v2/evc -d '{"name": "TENET_vlan_201_203_Ampath_Tenet", "dynamic_backup_path": true, "uni_a": {"tag": {"value": 203, "tag_type": 1}, "interface_id": "cc:00:00:00:00:00:00:07:41"}, "uni_z": {"tag": {"value": 201, "tag_type": 1}, "interface_id": "cc:00:00:00:00:00:00:08:50"}}'

**Comment by sajith** [comment]
This is in progress in #120.   Breakdown looks like below, as of 5ced9d1.

```json
{
    "urn:ogf:network:sdx:topology:zaoxi.net": {
        "name": "test-breakdown",
        "dynamic_backup_path": true,
        "uni_a": {
            "tag": {
                "value": 10001,
                "tag_type": 1
            },
            "port_id": "urn:ogf:network:sdx:port:zaoxi:A1:2"
        },
        "uni_z": {
            "tag": {
                "value": 10001,
                "tag_type": 1
            },
            "port_id": "urn:ogf:network:sdx:port:zaoxi:B1:1"
        }
    },
    "urn:ogf:network:sdx:topology:sax.net": {
        "name": "test-breakdown",
        "dynamic_backup_path": true,
        "uni_a": {
            "tag": {
                "value": 10001,
                "tag_type": 1
            },
            "port_id": "urn:ogf:network:sdx:port:sax:B3:1"
        },
        "uni_z": {
            "tag": {
                "value": 10001,
                "tag_type": 1
            },
            "port_id": "urn:ogf:network:sdx:port:sax:B1:1"
        }
    },
    "urn:ogf:network:sdx:topology:amlight.net": {
        "name": "test-breakdown",
        "dynamic_backup_path": true,
        "uni_a": {
            "tag": {
                "value": 10001,
                "tag_type": 1
            },
            "port_id": "urn:sdx:port:amlight:B1:1"
        },
        "uni_z": {
            "tag": {
                "value": 10001,
                "tag_type": 1
            },
            "port_id": "urn:sdx:port:amlight.net:A1:1"
        }
    }
}
```

Note that `interface_id` has been renamed to `port_id`, because nothing is known to PCE by the name "interface".   Also the tag values look funny -- looking into it.
