### ISSUE TITLE
Breakdowns must contain domains

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/pce#110]
`TEManager.generate_connection_breakdown()` tends to produces results like this:

```
{
    "null": {
        "ingress_port": {
            "id": "urn:ogf:network:sdx:port:sax:B1:2",
            "name": "Unknown",
            "short_name": null,
            "node": "urn:ogf:network:sdx:node:sax:B1",
            "label_range": null,
            "status": null,
            "state": null,
            "private_attributes": null
        },
        "egress_port": {
            "id": "urn:ogf:network:sdx:port:sax:B1:3",
            "name": "Novi01:3",
            "node": "urn:ogf:network:sdx:node:sax:B1",
            "short_name": "B1:3",
            "label_range": [
                "100-200",
                "10001"
            ],
            "status": "up"
        }
    }
}
```

In order to be useful, the outer key (`"null"` in this instance) should be refer to a domain (or perhaps a topology ID?).  It should not be `"null"`.

**Comment by YufengXin** [comment]
Yes. Plus the "label_range" should be "vlan", whose vlan is assigned by the vlan assignment function (#101). The problem might be that the port objects were directly referred from the topology object. It probably should be new instances with  further annotation? (Sorry for short comment due to the travel situation).

**Comment by sajith** [comment]
> Yes. Plus the "label_range" should be "vlan", whose vlan is assigned by the vlan assignment function (#101). The problem might be that the port objects were directly referred from the topology object. It probably should be new instances with further annotation? (Sorry for short comment due to the travel situation).

Yes, they are directly "inherited" from topology.  So perhaps pce will need to transform `label_range` to `vlan`?

**Comment by YufengXin** [comment]
Yes. The breakdown only needs to assign one vlan per connection which is what is needed by Kytos/oess.

**Comment by sajith** [comment]
Okay. I will follow that up separately.
