### ISSUE TITLE
Possible regression in multi-domain breakdown

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/pce#114]
It seems that [the original connection request](https://github.com/atlanticwave-sdx/pce/blob/main/tests/data/test_request.json) that we've been testing with used to be able to produce a breakdown that spans three domains, but now pce is unable to find a solution for the same connection request.

This is a follow up to issue #112 and PR #113.  It would be useful to get PR #113 merged first, to prevent it from growing anymore.  I ended up writing a test to investigate this issue in that PR.

**Comment by YufengXin** [comment]
The original topology json model is first converted to a  networkx graph model, before forming the PCE optimization model. It would be useful to debug on the networkx graph model first, eg, generating the graph in a image, mapping the connection request to this graph to see if a path exist or not, etc.

**Comment by YufengXin** [comment]
Added a comment in SDX-controller:

https://github.com/atlanticwave-sdx/sdx-controller/issues/145
