### ISSUE TITLE
Re-compute available bandwidth 

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/pce#162]
When pce attempts to satisfy a connection request, it needs to subtract the allocated bandwidth from the available bandwidth, so that subsequent requests can be satisfied correctly from the available remaining bandwith.

**Comment by YufengXin** [comment]
Changes in the spec on the link object in topology json:
"The bandwidth attribute describes the maximum capacity in terms of bandwidth of a Link object. The bandwidth of a link could be the interface’s bandwidth or a leased capacity provided by a carrier to the OXP. Bandwidth must represent how much bandwidth capacity is accessible to be used by the SDX community in units of Gbps. For instance, a 50 Gbps link must have the attribute bandwidth set to 50. bandwidth accepts a fractional value. For instance, for a 500 Mbps or 3250 Mbps link, bandwidth must be converted to Gbps, with values 0.5 and 3.25 respectively.

The residual_bandwidth attribute describes the average bandwidth available for the Link object. The representation of the residual_bandwidth must be provided in percentage from 0 to 100 of the bandwidth attribute. For instance, if bandwidth is 40Gbps and the Link average utilization is 25Gbps (or 62.5%), the residual_bandwidth must have value 37.5, meaning 37.5%. The OXP operator is responsible for defining the time interval to be based, for instance, the last 30 days, the last day, or the last 12 hours. This specification suggests that residual_bandwidth to be based on the last 7 to 14 days for better accuracy and decision making."

**Comment by YufengXin** [comment]
Here is the update function: graph = solver.update_graph(graph, ordered_paths)
It needs to be called somewhere...
