### ISSUE TITLE
Check form for vlan_range - error ValidationError("Label must be a string.")

### ISSUE THREAD

**Issue by italovalcy** [atlanticwave-sdx/pce#189]
hi,

According to the [Topology Data Model spec 2.0](https://docs.google.com/document/d/1lgxjIT144EFu1G_OVcU19hN1cSUT_v2-tE0Z-7UlkNg/edit#heading=h.3e80ch10jnd3), the `vlan_range` attribute under services/l2vpn-ptp or services/l2vpn-ptmp should be in the following format:

```
The "vlan_range" key under "l2vpn-ptp" and "l2vpn-ptmp" is a comma-delimited list of tuples, where each tuple's element 0 is the first VLAN ID of the range and the tuple's element 1 is the last VLAN ID of the range. Multiple tuples can be provided in any sequence. The minimum VLAN ID supported is 1 and the maximum VLAN ID supported is 4095.
```

Please check the [provided example](https://docs.google.com/document/d/1lgxjIT144EFu1G_OVcU19hN1cSUT_v2-tE0Z-7UlkNg/edit#bookmark=id.9ubxxqxov5nt)

However, the PCE is trying to consume the vlan_range field in the same way it used to be with "label_range" field:
1. First, it tries to get the services/l2vpn-ptp (https://github.com/atlanticwave-sdx/pce/blob/main/src/sdx_pce/topology/temanager.py#L191)
2. if no services/l2vpn-ptp is found then it fallback to the "label_range" field (https://github.com/atlanticwave-sdx/pce/blob/main/src/sdx_pce/topology/temanager.py#L193)
3. in both cases, the value for the supported VLAN range is processed as a list of strings (https://github.com/atlanticwave-sdx/pce/blob/main/src/sdx_pce/topology/temanager.py#L212), which is not correct

If we are trying to make the PCE backward compatible with the previous spec, maybe we should process the returned VLAN range in different ways (list of strings, versus list of tuples), or even make the code aware of both formats.

Anyway, if the topology sent from the OXP to SDX-LC contains the format specified by Topology DataModel Spec 2.0, the SDX-Controller will refuse to process the topology with the following error:

```
sdx-controller  | Exception in thread Thread-2:
sdx-controller  | Traceback (most recent call last):
sdx-controller  |   File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
sdx-controller  |     self.run()
sdx-controller  |   File "/usr/local/lib/python3.9/threading.py", line 917, in run
sdx-controller  |     self._target(*self._args, **self._kwargs)
sdx-controller  |   File "/usr/src/app/sdx_controller/messaging/rpc_queue_consumer.py", line 135, in start_sdx_consumer
sdx-controller  |     lc_message_handler.process_lc_json_msg(
sdx-controller  |   File "/usr/src/app/sdx_controller/handlers/lc_message_handler.py", line 58, in process_lc_json_msg
sdx-controller  |     self.te_manager.add_topology(msg_json)
sdx-controller  |   File "/usr/local/lib/python3.9/site-packages/sdx_pce/topology/temanager.py", line 78, in add_topology
sdx-controller  |     self._update_vlan_tags_table(
sdx-controller  |   File "/usr/local/lib/python3.9/site-packages/sdx_pce/topology/temanager.py", line 160, in _update_vlan_tags_table
sdx-controller  |     all_labels = self._expand_label_range(label_range)
sdx-controller  |   File "/usr/local/lib/python3.9/site-packages/sdx_pce/topology/temanager.py", line 216, in _expand_label_range
sdx-controller  |     labels = [self._expand_label(label) for label in label_range]
sdx-controller  |   File "/usr/local/lib/python3.9/site-packages/sdx_pce/topology/temanager.py", line 216, in <listcomp>
sdx-controller  |     labels = [self._expand_label(label) for label in label_range]
sdx-controller  |   File "/usr/local/lib/python3.9/site-packages/sdx_pce/topology/temanager.py", line 229, in _expand_label
sdx-controller  |     raise ValidationError("Label must be a string.")
sdx-controller  | sdx_pce.utils.exceptions.ValidationError: Label must be a string.
```

How to reproduce:
1. Using sdx-controller from main branch
2. Using the topology sent by SDX-LC following the format from Topology Data Model Spec 2.0 (Like the example here: https://docs.google.com/document/d/1lgxjIT144EFu1G_OVcU19hN1cSUT_v2-tE0Z-7UlkNg/edit#bookmark=id.9ubxxqxov5nt)

**Comment by YufengXin** [comment]
@italovalcy 
(1) In the example in the spec: one port uses [[1,100], [300,305], [1000,1500]], another port uses [(1,4000)]. 

(2) strictly speaking, JSON schema standard uses minimum and maximum properties to define a numerical range. (that's why I originally used them our json schemas):

https://json-schema.org/understanding-json-schema/reference/numeric

For now I'll add support for tuples.

@sajith

**Comment by sajith** [comment]
@italovalcy Italo, the spec is incorrect there, because `(1, 1000)` (for example) is not valid JSON (although it is a valid Python tuple).   The [JSON specification](https://www.json.org/json-en.html) does not have tuples.  You can try feeding the example to `json.loads()` and see for yourself.  We will have to make do with `[1, 1000]` or some other form.

I had made this comment during the draft stage of datamodel 2.0.0 spec. My comment seems to have gone unresolved.  I can't find the comment or the draft document anymore.

**Comment by italovalcy** [comment]
> @italovalcy Italo, the spec is incorrect there, because `(1, 1000)` (for example) is not valid JSON (although it is a valid Python tuple). The [JSON specification](https://www.json.org/json-en.html) does not have tuples. You can try feeding the example to `json.loads()` and see for yourself. We will have to make do with `[1, 1000]` or some other form.
> 
> I had made this comment during the draft stage of datamodel 2.0.0 spec. My comment seems to have gone unresolved. I can't find the comment or the draft document anymore.

Hi @YufengXin and @sajith good catch! I agree with Sajith with his comment on the representation of the tuples to comply with JSON spec. Let’s please move forward with the characters `()`  being replaced by `[]` . Example:

```
			"services": {
                    "l2vpn-ptp": { 
                       "vlan_range": [[1,4000]]
                    },
                    "l2vpn-ptmp": { 
                       "vlan_range": [[1,1000], [2000,3000]]
                    } 
                 },

```
I’ve updated the data model spec accordingly

**Comment by YufengXin** [comment]
resolved
