### ISSUE TITLE
Persistent vlan resource between SDX-controller restart

### ISSUE THREAD

**Issue by YufengXin** [atlanticwave-sdx/pce#215]
Doublecheck: this might be implemented in sdx-controller: needs save the vlan resource use in DB so that it is persistent after sdx-controller restart.

**Comment by sajith** [comment]
We will need to add a method (something like `TEManager.restore_vlan_reservations(..)`), and sdx-controller will need to call that after a restart, I think?

**Comment by YufengXin** [comment]
will you need a persistent storage for used vlan recovery? should be implemented in MondoDB in sdx-controller? or just local? I think?

**Comment by sajith** [comment]
If PCE is going to stay a library the way it is today, it should not use a database.  It should be up to sdx-controller to restore the previous state.  I have not thought much about what sdx-controller would need to store, but I suppose it should be straightforward.  This probably is the sensible medium-term plan.

If PCE becomes a stand-alone service, its application logic could use a database.

**Comment by YufengXin** [comment]
Next step: make two methods for sdx-controller: get_available_vlans():-> {domain:available_vlans} and set_available_vlans({domain:available_vlans})

six-controller will call and save/pop the info to/from the DB.
