### ISSUE TITLE
Support for VLAN ranges, "all", and "untagged"

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/pce#224]
`vlan` values in connection requests can be of the form `"{number}"`, `"{number}:{number}"` (representing a range), `"any"`, `"all"`, or `"untagged"`.  See the discussion about vlan under [L2VPN Mandatory Attributes](https://sdx-docs.readthedocs.io/en/latest/specs/provisioning-api-1.0.html#mandatory-attributes).

These probably should have child tickets, so that we can implement them in smaller steps.  When https://github.com/atlanticwave-sdx/pce/pull/223 gets merged, `"{number}"` and `"any"` should be handled.

**Comment by YufengXin** [comment]
This is resolved in 
PR #223 (https://github.com/atlanticwave-sdx/pce/pull/223)
