### ISSUE TITLE
Refactor `global_name.py`

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/pce#68]
- Should follow the [PEP 8 suggestion regarding constants](https://peps.python.org/pep-0008/#constants). It says: "constants are usually defined on a module level and written in all capital letters with underscores separating words."
- Document the constants? 
- Perhaps this module can be named `constants`?

See #56.

**Comment by YufengXin** [comment]
I think some issues like this one are complete and should be closed.

**Comment by sajith** [comment]
True. This is addressed in #84.
