### ISSUE TITLE
Refactor `randomTopologyGenerator.py`

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/pce#70]
In `weight_assign()` method, using constants (such as `LINK_WEIGHT_BANDWIDTH`, `LINK_WEIGHT_LATENCY`, and so on) for the flags would be clearer to read:

https://github.com/atlanticwave-sdx/pce/blob/9c3be7f4355104eea7d97bba595522758fe9bbc3/src/Utility/randomTopologyGenerator.py#L118-L137

**Comment by YufengXin** [comment]
You complete it already-:)
