### ISSUE TITLE
Remove unused code

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/pce#85]
According to [test coverage report](https://coveralls.io/builds/55711216), we have some under-tested code:

![image](https://user-images.githubusercontent.com/23618/211314700-54124d6d-ba5c-4943-899c-a7976386e63b.png)

The test coverage should be improved (്#71) for the code that is actually useful, and the code that is not likely to be used should be removed.  Some likely candidates:

- `weight_assign()` seems to be duplicated across `utils.functions` and `utils.random_topology_generator`, and the latter is never actually used:

https://github.com/atlanticwave-sdx/pce/blob/85d3a279b98c1c06ca5799e59823ff5b49e52e78/src/sdx/pce/utils/random_topology_generator.py#L119

https://github.com/atlanticwave-sdx/pce/blob/85d3a279b98c1c06ca5799e59823ff5b49e52e78/src/sdx/pce/utils/functions.py#L30

- Functions that seem to relate to backup path computation, in `utils.functions`.
- `random()`, `linear_grouping()`, `geometric_grouping()`, and `alt_geometric_grouping()` in `utils.random_connection_generator`.

**Comment by YufengXin** [comment]
1. weight_assign() in utils.functions can be removed. But it's useful in utils.random_topology_generator
2. random(), linear_grouping(), geometric_grouping(), and alt_geometric_grouping() in utils.random_connection_generator are useful.

The deal is that this repo is a library and some functions are supposed to be used by SDX-controller or SDX-LC, not necessarily internally in this repo. It's true that we need to add more unitests for useful functions.

**Comment by YufengXin** [comment]
And we'll add/complete more functions, for example, the backup path computation function will be useful, but the implementation is not completed yet. 

Overall, this is a repo under active development.

**Comment by sajith** [comment]
@YufengXin Thanks!  I guess I lost the plot a bit here -- I was thinking that random topology/connection generators are strictly useful in testing pce's path computation API, and not necessarily elsewhere.

**Comment by sajith** [comment]
@YufengXin The `weight_assign()` method in `utils.functions` is used in two places:

https://github.com/atlanticwave-sdx/pce/blob/dd9dca953b51a66366e9c25992501acedccb8f40/src/sdx/pce/load_balancing/te_solver.py#L26

https://github.com/atlanticwave-sdx/pce/blob/dd9dca953b51a66366e9c25992501acedccb8f40/src/sdx/pce/utils/random_topology_generator.py#L96

... whereas the `weight_assign()` in `utils.random_topology_generator` is not actually used.
